# Generated by Django 2.0.5 on 2018-10-04 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hitcount.models
import mysite.storage_backends
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propicker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='사진이름')),
                ('genre', models.CharField(max_length=20, verbose_name='장르')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(storage=mysite.storage_backends.MediaStorage(), upload_to='orgin')),
                ('img_thumbnail_h', models.ImageField(blank=True, storage=mysite.storage_backends.MediaStorage(), upload_to='thumbnail/high')),
                ('img_thumbnail_d', models.ImageField(blank=True, storage=mysite.storage_backends.MediaStorage(), upload_to='thumbnail/down')),
                ('img_thumbnail_f', models.ImageField(blank=True, storage=mysite.storage_backends.MediaStorage(), upload_to='thumbnail/free')),
                ('content', models.TextField(max_length=260, null=True, verbose_name='사진 소개')),
                ('tag', tagging.fields.TagField(blank=True, max_length=255)),
                ('price', models.IntegerField(default=0, verbose_name='사진 금액')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='사진 작성일')),
                ('modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='사진 수정일')),
                ('download_count', models.IntegerField(default=0, verbose_name='다운로드횟수')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('like_user_set', models.ManyToManyField(blank=True, related_name='like_user_set', through='gallery.Like', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propicker.Propicker')),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.AddField(
            model_name='like',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Photo'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
