# Generated by Django 2.0.5 on 2018-10-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='img_thumbnail_h',
            new_name='img_thumbnail',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='img_thumbnail_d',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='img_thumbnail_f',
        ),
    ]
