# Generated by Django 2.0.5 on 2018-10-06 07:17

from django.db import migrations, models
import mysite.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20181004_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='img_thumbnail_d',
            field=models.ImageField(blank=True, storage=mysite.storage_backends.MediaStorage(), upload_to='thumbnail/down'),
        ),
        migrations.AddField(
            model_name='photo',
            name='img_thumbnail_f',
            field=models.ImageField(blank=True, storage=mysite.storage_backends.MediaStorage(), upload_to='thumbnail/free'),
        ),
    ]
