# Generated by Django 2.0.5 on 2018-10-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_total_price'),
        ('gallery', '0003_auto_20181006_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='cart_add',
            field=models.ManyToManyField(blank=True, related_name='cart_add_set', through='cart.PhotoDetail', to='cart.Cart'),
        ),
    ]
