# Generated by Django 2.0.5 on 2018-10-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_photo_cart_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='genre',
            field=models.IntegerField(choices=[(0, '동물'), (1, '사람'), (2, '사물'), (3, '풍경/자연'), (4, '음식'), (5, '여행'), (6, '계절'), (7, '날씨'), (8, '건축'), (9, '동적 이미지'), (10, '기타')], verbose_name='장르'),
        ),
    ]
