# Generated by Django 2.0.7 on 2018-10-04 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propicker', '0001_initial'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(max_length=256, verbose_name='답변내용')),
                ('answer_create_date', models.DateTimeField(auto_now_add=True, verbose_name='답변 작성일')),
            ],
            options={
                'verbose_name': '답변',
                'verbose_name_plural': '답변모음',
                'ordering': ['question_title'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=100, unique=True, verbose_name='질문제목')),
                ('question_text', models.TextField(max_length=256, verbose_name='질문내용')),
                ('question_create_date', models.DateTimeField(auto_now_add=True, verbose_name='질문작성일')),
                ('propicker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propicker.Propicker')),
            ],
            options={
                'verbose_name': '질문',
                'verbose_name_plural': '질문모음',
                'ordering': ['propicker_id'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(max_length=100, verbose_name='신고자 이름')),
                ('reporter_email', models.CharField(max_length=100, verbose_name='신고자 메일주소')),
                ('reporter_number', models.CharField(max_length=100, verbose_name='신고자 연락처')),
                ('report_text', models.TextField(max_length=256, verbose_name='신고내용')),
                ('report_file', models.FileField(blank=True, null='True', upload_to='report/', verbose_name='첨부파일')),
                ('report_type', models.CharField(max_length=100, verbose_name='신고유형')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='신고일자')),
                ('report_result', models.BooleanField(default=False)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Report_photo', to='gallery.Photo')),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
                'ordering': ['create_date', 'reporter'],
            },
        ),
        migrations.CreateModel(
            name='ReportResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punish', models.IntegerField(choices=[(0, '징계없음'), (1, '회원 정지 3개월'), (2, '회원 영구 정지')], default=0, verbose_name='징계여부')),
                ('context', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.Report')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.Question'),
        ),
    ]
