# Generated by Django 2.0.5 on 2018-10-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportresult',
            name='report',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_result',
        ),
        migrations.AddField(
            model_name='report',
            name='punish',
            field=models.IntegerField(blank=True, choices=[(0, '징계없음'), (1, '회원 정지 3개월'), (2, '회원 영구 정지')], default=0, verbose_name='징계여부'),
        ),
        migrations.DeleteModel(
            name='ReportResult',
        ),
    ]
