# Generated by Django 2.0.5 on 2018-10-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_auto_20181006_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='photo',
            field=models.CharField(max_length=256, verbose_name='게시물 url'),
        ),
    ]
