# Generated by Django 2.0.7 on 2018-11-01 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_auto_20181006_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='propicker.Propicker'),
        ),
    ]
