# Generated by Django 2.0.7 on 2018-11-01 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_auto_20181101_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propicker.Propicker'),
        ),
    ]
