# Generated by Django 2.0.5 on 2018-10-04 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mysite.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_login', models.BooleanField(default=False, verbose_name='로그인유지여부')),
                ('name', models.CharField(max_length=30, verbose_name='회원이름')),
                ('phone', models.CharField(max_length=30, null=True, verbose_name='회원 전화번호')),
                ('birth', models.DateField(null=True, verbose_name='생년월일')),
                ('isMale', models.BooleanField(choices=[(True, '남자'), (False, '여자')], default=True, verbose_name='성별(Default: 남자)')),
                ('content', models.TextField(max_length=200, null=True, verbose_name='회원소개')),
                ('upload', models.FileField(storage=mysite.storage_backends.Public1MediaStorage(), upload_to='')),
                ('user_state', models.CharField(choices=[('no', '일반'), ('pa', '일시정지'), ('st', '영구정지'), ('qt', '탈퇴')], default='no', max_length=2, verbose_name='회원상태')),
                ('kakao_use', models.BooleanField(default=False, verbose_name='카카오사용여부')),
                ('naver_use', models.BooleanField(default=False, verbose_name='네이버사용여부')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '회원코드',
                'verbose_name_plural': '회원코드모음',
                'ordering': ['pk'],
            },
        ),
    ]
