# Generated by Django 2.0.7 on 2018-10-05 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propicker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propicker',
            options={'ordering': ['pk'], 'verbose_name': 'propicker', 'verbose_name_plural': 'propickers'},
        ),
    ]
