# Generated by Django 2.0.5 on 2018-10-06 16:56

from django.db import migrations, models
import mysite.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('propicker', '0003_auto_20181007_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propicker',
            name='upload',
            field=models.FileField(blank=True, storage=mysite.storage_backends.Public1MediaStorage(), upload_to=''),
        ),
    ]
