# Generated by Django 2.0.7 on 2018-10-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propicker', '0006_propicker_email_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account_num', models.IntegerField(verbose_name='계좌번호')),
                ('user_account_bank', models.CharField(max_length=10, verbose_name='은행이름')),
                ('propicker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propicker.Propicker')),
            ],
        ),
    ]
