# Generated by Django 2.0.7 on 2018-10-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propicker', '0002_auto_20181005_1116'),
        ('propicker', '0008_auto_20181008_2333'),
    ]

    operations = [
    ]
