# Generated by Django 2.0.7 on 2018-10-08 14:49

from django.db import migrations, models
import mysite.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('propicker', '0009_merge_20181008_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propicker',
            options={'ordering': ['pk'], 'verbose_name': '회원코드', 'verbose_name_plural': '회원코드모음'},
        ),
        migrations.AlterField(
            model_name='propicker',
            name='upload',
            field=models.FileField(blank=True, storage=mysite.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
