# Generated by Django 2.0.5 on 2018-10-29 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propicker', '0012_auto_20181010_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receive_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propicker.Propicker')),
            ],
        ),
        migrations.AddField(
            model_name='propicker',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, related_name='likes_user_set', through='propicker.UserLike', to='propicker.Propicker'),
        ),
    ]
