# Generated by Django 2.0.5 on 2018-10-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propicker', '0013_auto_20181029_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propicker',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, related_name='like_users_set', through='propicker.UserLike', to='propicker.Propicker'),
        ),
    ]
