# Generated by Django 2.0.5 on 2018-10-29 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propicker', '0014_auto_20181029_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlike',
            name='like_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_propicker', to='propicker.Propicker'),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='receive_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_propicker', to='propicker.Propicker'),
        ),
    ]
