# Generated by Django 2.0.7 on 2018-11-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propicker', '0017_auto_20181101_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propicker',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
    ]
