# Generated by Django 2.0.7 on 2018-10-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photodetail',
            options={'ordering': ('pk',), 'verbose_name': 'detail', 'verbose_name_plural': 'details'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.PositiveIntegerField(verbose_name='결제금액'),
        ),
        migrations.AlterField(
            model_name='photodetail',
            name='quality_price',
            field=models.PositiveIntegerField(default=0, verbose_name='화질별 금액'),
        ),
    ]
