# Generated by Django 2.0.7 on 2018-10-30 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20181020_0206'),
        ('cart', '0005_auto_20181030_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='photo',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_one', to='gallery.Photo'),
        ),
    ]
