# Generated by Django 2.0.7 on 2018-10-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_payment_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='merchant_uid',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='고유주문번호'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(max_length=20, null=True, verbose_name='결제방식'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='결제금액'),
        ),
    ]
