# Generated by Django 2.0.5 on 2018-10-04 06:04

from django.db import migrations, models
import mysite.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_title', models.CharField(max_length=30, verbose_name='테마명')),
                ('theme_img', models.FileField(storage=mysite.storage_backends.PublicMediaStorage(), upload_to='')),
                ('theme_content', models.TextField(verbose_name='테마설명')),
                ('theme_create_date', models.DateTimeField(auto_now_add=True, verbose_name='테마 작성일')),
                ('theme_modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='테마 수정일')),
                ('photo_id', models.ManyToManyField(to='gallery.Photo')),
            ],
            options={
                'verbose_name': '테마',
                'verbose_name_plural': '테마모음',
                'ordering': ['pk'],
            },
        ),
    ]
